In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
root = os.getcwd()
root

'./fair_taucc/datasets/movielens/movielens-1m'

In [5]:
matrix = np.load(root + "/matrix.npy")
matrix

array([[5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]])

In [6]:
ratings = pd.read_csv(root + "/ratings.dat", sep="::", header=None, names=["user_id", "movie_id", "user_rating", "timestamp"])
ratings

/tmp/ipykernel_260880/3868375512.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  ratings = pd.read_csv(root + "/ratings.dat", sep="::", header=None, names=["user_id", "movie_id", "user_rating", "timestamp"])


user_id  movie_id  user_rating  timestamp
0              1      1193            5  978300760
1              1       661            3  978302109
2              1       914            3  978301968
3              1      3408            4  978300275
4              1      2355            5  978824291
...          ...       ...          ...        ...
1000204     6040      1091            1  956716541
1000205     6040      1094            5  956704887
1000206     6040       562            5  956704746
1000207     6040      1096            4  956715648
1000208     6040      1097            4  956715569

[1000209 rows x 4 columns]

In [10]:
movie_id = np.sort(np.unique(ratings["movie_id"]))
movie_id

array([   1,    2,    3, ..., 3950, 3951, 3952])

In [11]:
num_movies = movie_id.shape[0]
num_movies

3706

In [12]:
movies_dict = {
    "id_movie": movie_id,
    "id_col": np.arange(0, num_movies)
}

In [13]:
df_movies_map = pd.DataFrame(movies_dict)
df_movies_map

id_movie  id_col
0            1       0
1            2       1
2            3       2
3            4       3
4            5       4
...        ...     ...
3701      3948    3701
3702      3949    3702
3703      3950    3703
3704      3951    3704
3705      3952    3705

[3706 rows x 2 columns]

In [14]:
user_id = np.sort(np.unique(ratings["user_id"]))
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [15]:
num_users = user_id.shape[0]
num_users

6040

In [16]:
users_dict = {
    "id_user": user_id,
    "id_row": np.arange(0, num_users)
}

In [17]:
df_users_map = pd.DataFrame(users_dict)
df_users_map

id_user  id_row
0           1       0
1           2       1
2           3       2
3           4       3
4           5       4
...       ...     ...
6035     6036    6035
6036     6037    6036
6037     6038    6037
6038     6039    6038
6039     6040    6039

[6040 rows x 2 columns]

In [18]:
df_movies_map.to_csv(root + "/mapping_movies.csv", index=False)
df_users_map.to_csv(root + "/mapping_users.csv", index=False)