In [342]:
import numpy as np
import os

import sys
sys.path.append('./fair_taucc/tauCC/src')
from fairness_metrics import balance_gen, balance_chierichetti, KL_fairness_error

In [343]:
matrix = np.array([
    [5,0,0,0,4],
    [4,0,0,0,0],
    [0,2,0,5,0],
    [0,5,4,0,0],
    [0,0,5,0,0],
    [0,0,0,4,5]
])

In [344]:
sensitive = np.array([0,0,1,1,0,1])

In [350]:
from tauCC.src.taucc.taucc import CoClust
model = CoClust(initialization='random', verbose=True, random_state=40, k=3, l=4)
model.fit(matrix)

Initialization step for (6,5)-siezed input matrix.
iteration 0, moving rows, n_clusters: (3, 3), n_moves: 3
Values of tau_x: 0.4650 and tau_y: 0.4209, for (3,3)-sized T at iteration: 0 (on rows).
iteration 1, moving rows, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.4650 and tau_y: 0.4209, for (3,3)-sized T at iteration: 0 (on rows).
iteration 2, moving columns, n_clusters: (3, 3), n_moves: 1
Values of tau_x: 0.6245 and tau_y: 0.6697, for (3,3)-sized T at iteration: 0 (on columns).
iteration 3, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.6245 and tau_y: 0.6697, for (3,3)-sized T at iteration: 0 (on columns).
iteration 4, moving rows, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.6245 and tau_y: 0.6697, for (3,3)-sized T at iteration: 1 (on rows).
iteration 5, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.6245 and tau_y: 0.6697, for (3,3)-sized T at iteration: 1 (on columns).
Final values of tau_x: 0.6245 and tau_y: 0.6697, for (3,3)-si

In [351]:
model.tau_x

[0.1304444444444445,
 0.46495114006514643,
 0.46495114006514643,
 0.6245475931958014,
 0.6245475931958014,
 0.6245475931958014,
 0.6245475931958014]

In [352]:
model.tau_y

[0.15287255117763607,
 0.4208535108958838,
 0.4208535108958838,
 0.6697180134680134,
 0.6697180134680134,
 0.6697180134680134,
 0.6697180134680134]

In [353]:
model.column_labels_

[0, 1, 1, 2, 0]

In [354]:
row_labels_vanilla = model.row_labels_
row_labels_vanilla

[2, 2, 0, 1, 1, 0]

In [355]:
balance_gen(sensitive, row_labels_vanilla)

0.0

In [356]:
balance_chierichetti(sensitive, row_labels_vanilla)

0

In [321]:
from tauCC.src.taucc.taucc_fair_v3_tau_fairness import FairCoclusRows
model = FairCoclusRows(initialization='random', verbose=True, k=3, l=4)
model.fit(matrix, sensitive, fair_parameters=np.array([1.0,1.0]))

ratio groups in dataset: [0.5, 0.5]
Initialization step for (6,5)-sized input matrix.
fair row assignment: 
[0 2 2 1 1 0]
iteration 0, moving rows, n_clusters: (3, 4), n_moves: 2
Values of tau_x: 0.4725 and tau_y: 0.2756, for (3,4)-sized T at iteration: 0 (on rows).
iteration 1, moving rows, n_clusters: (3, 4), n_moves: 0
Values of tau_x: 0.4725 and tau_y: 0.2756, for (3,4)-sized T at iteration: 0 (on rows).
iteration 2, moving columns, n_clusters: (3, 3), n_moves: 2
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 0 (on columns).
iteration 3, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 0 (on columns).
iteration 4, moving rows, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 1 (on rows).
iteration 5, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 1 (on 

In [322]:
model.tau_x

[0.5192957249445451,
 0.47248666298749065,
 0.47248666298749065,
 0.555049668874172,
 0.555049668874172,
 0.555049668874172,
 0.555049668874172]

In [323]:
model.tau_y

[0.3499665551839463,
 0.27563465341243115,
 0.27563465341243115,
 0.555785123966942,
 0.555785123966942,
 0.555785123966942,
 0.555785123966942]

In [324]:
model.column_labels_

[2, 1, 1, 2, 0]

In [325]:
row_labels = model.row_labels_
print("index: ", list(range(len(row_labels))))
print("clust: ", row_labels)
print("sensi: ", list(sensitive))

index:  [0, 1, 2, 3, 4, 5]
clust:  [0, 2, 2, 1, 1, 0]
sensi:  [0, 0, 1, 1, 0, 1]


In [326]:
balance_gen(sensitive, row_labels)

1.0

In [327]:
balance_chierichetti(sensitive, row_labels)

1.0

In [335]:
from tauCC.src.taucc.taucc_fair_v3_tau_fairness import FairCoclusRows
model = FairCoclusRows(initialization='random', verbose=True, random_state=40, k=3, l=4)
model.fit(matrix, sensitive, fair_parameters=np.array([1.0,1.0]))

ratio groups in dataset: [0.5, 0.5]
Initialization step for (6,5)-sized input matrix.
fair row assignment: 
[2 0 0 1 1 2]
iteration 0, moving rows, n_clusters: (3, 3), n_moves: 3
Values of tau_x: 0.3178 and tau_y: 0.2669, for (3,3)-sized T at iteration: 0 (on rows).
fair row assignment: 
[2 0 0 1 1 2]
iteration 1, moving rows, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.3178 and tau_y: 0.2669, for (3,3)-sized T at iteration: 0 (on rows).
iteration 2, moving columns, n_clusters: (3, 3), n_moves: 2
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 0 (on columns).
iteration 3, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 0 (on columns).
iteration 4, moving rows, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, for (3,3)-sized T at iteration: 1 (on rows).
iteration 5, moving columns, n_clusters: (3, 3), n_moves: 0
Values of tau_x: 0.5550 and tau_y: 0.5558, fo

In [336]:
model.tau_x

[0.1304444444444445,
 0.317821927888153,
 0.317821927888153,
 0.555049668874172,
 0.555049668874172,
 0.555049668874172,
 0.555049668874172]

In [337]:
model.tau_y

[0.15287255117763607,
 0.26692129799474446,
 0.26692129799474446,
 0.555785123966942,
 0.555785123966942,
 0.555785123966942,
 0.555785123966942]

In [338]:
model.column_labels_

[2, 1, 1, 2, 0]

In [339]:
row_labels = model.row_labels_
print("index: ", list(range(len(row_labels))))
print("clust: ", row_labels)
print("sensi: ", list(sensitive))

index:  [0, 1, 2, 3, 4, 5]
clust:  [2, 0, 0, 1, 1, 2]
sensi:  [0, 0, 1, 1, 0, 1]


In [340]:
balance_gen(sensitive, row_labels)

1.0

In [341]:
balance_chierichetti(sensitive, row_labels)

1.0